# Generated by Django 2.2.9 on 2021-03-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='addr',
            field=models.CharField(default='BeijingRoad', max_length=128),
        ),
    ]
