# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-24 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='prince',
            new_name='price',
        ),
    ]
